development:
  sessions:
    default:
      database: mongoid_sortable_relation_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: mongoid_sortable_relation_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: mongoid_sortable_relation
      hosts:
        - localhost:27017